### ISSUE TITLE
Laboratory Work #0

### ISSUE THREAD

**Issue by KozyrevychYaroslav** [oleksandrblazhko/ai182-kozirevich#1]

**Comment by oleksandrblazhko** [comment]
Відомо, що безпечна клієнт-серверна взаємодія може забезпечуватися через наступні
ключи: відкритий ключ клієнта, закритий ключ клієнта, відкритий ключ сервера, закритий ключ
сервера. Вкажіть, будь ласка, який ключ вами було використано під час налаштування безпечного
оновлення GitHub-репозиторію змінами з локального Git-репозиторію.

**Comment by KozyrevychYaroslav** [comment]
Відкритий ключ клієнта SSH

**Comment by oleksandrblazhko** [comment]
2
